name = "centinela-api"
main = "src/index.js"
compatibility_date = "2025-07-01"

[vars]
# VirusTotal API key (obligatoria)
# VIRUSTOTAL_API_KEY = "tu_clave_vt"

# Google Safe Browsing API key (opcional — fallback #1)
# GSB_API_KEY = "tu_clave_gsb"
